// lib/ratings.js — video-game overall ratings looked up from committed maps
// (data/ratings/<sport>.json, name -> OVR), so the live server never pages
// EA/Sony at runtime. Maps are generated by `npm run gen-ratings` and committed
// (like the seeds). NFL/Madden is handled separately in lib/nfl.js.
//
// Coverage: MLS → EA Sports FC, MLB → MLB The Show. NBA/WNBA (2K) and NHL/CFB
// have no publicly accessible ratings feed, so they carry no map (and no badge).
const fs = require("fs");
const path = require("path");
const { normName } = require("./nfl-util.js");

const DIR = path.join(__dirname, "..", "data", "ratings");
// CFB is wired to EA College Football, but EA doesn't publish those ratings via
// the public API yet (the endpoint returns 0 items) — so cfb.json is empty today
// and no badge shows. `publisher()` only returns a label when the map has data,
// so the moment EA populates it and `npm run gen-ratings` is re-run, CFB lights
// up automatically. (CBB has no video game with public ratings, so it's absent.)
const PUBLISHER = { mls: "EA FC", mlb: "MLB The Show", cfb: "EA College Football" };
const cache = {};

function load(sport) {
  if (sport in cache) return cache[sport];
  try { cache[sport] = JSON.parse(fs.readFileSync(path.join(DIR, `${sport}.json`), "utf8")); }
  catch { cache[sport] = null; }
  return cache[sport];
}

// The player's current OVR, or null if unknown / no map for this sport.
function ratingFor(sport, name) {
  const m = load(sport);
  if (!m || !name) return null;
  const v = m[normName(name)];
  return typeof v === "number" ? v : null;
}

// Which game a sport's ratings come from (for the "OVR" badge label), or null.
// Returns null when the sport has no map data yet, so a wired-but-empty source
// (e.g. CFB today) shows no badge until it's populated.
function publisher(sport) {
  if (!PUBLISHER[sport]) return null;
  const m = load(sport);
  return m && Object.keys(m).length ? PUBLISHER[sport] : null;
}

module.exports = { ratingFor, publisher };
