// lib/ratings.js — video-game overall ratings looked up from committed maps
// (data/ratings/<sport>.json, name -> OVR), so the live server never pages
// EA/Sony at runtime. Maps are generated by `npm run gen-ratings` and committed
// (like the seeds). NFL/Madden is handled separately in lib/nfl.js.
//
// Coverage: MLS → EA Sports FC, MLB → MLB The Show. NBA/WNBA (2K) and NHL/CFB
// have no publicly accessible ratings feed, so they carry no map (and no badge).
const fs = require("fs");
const path = require("path");
const { normName } = require("./nfl-util.js");

const DIR = path.join(__dirname, "..", "data", "ratings");
// CFB is wired to EA College Football, but EA doesn't publish those ratings via
// the public API yet (the endpoint returns 0 items) — so cfb.json is empty today
// and no badge shows. `publisher()` only returns a label when the map has data,
// so the moment EA populates it and `npm run gen-ratings` is re-run, CFB lights
// up automatically. (CBB has no video game with public ratings, so it's absent.)
const PUBLISHER = {
  mls: "EA FC", mlb: "MLB The Show", cfb: "EA College Football",
  // International soccer leagues — each has its own per-league EA FC map so a
  // same-named player from another league can't be mismatched. (Champions League
  // has no per-league map, so it carries no badge.)
  epl: "EA FC", laliga: "EA FC", bundesliga: "EA FC", seriea: "EA FC", ligue1: "EA FC", nwsl: "EA FC",
};
const cache = {};

// Map file key: current = "<sport>"; a past season = "<sport>-<year>" (only MLB
// has per-season maps, from MLB The Show's per-year sites — EA FC/Madden expose
// only the current edition).
const mapKey = (sport, year) => (year ? `${sport}-${year}` : sport);

function load(key) {
  if (key in cache) return cache[key];
  try { cache[key] = JSON.parse(fs.readFileSync(path.join(DIR, `${key}.json`), "utf8")); }
  catch { cache[key] = null; }
  return cache[key];
}

// Fold a name past normName: also flatten special letters normName's accent-strip
// misses (ı ł ø đ ß æ œ ð þ) and treat hyphens as spaces, so "Yıldız"/"Min-Jae"
// match "Yildiz"/"Min Jae".
const SPECIAL = { "ı": "i", "ł": "l", "ø": "o", "đ": "d", "ß": "ss", "æ": "ae", "œ": "oe", "ð": "d", "þ": "th", "ħ": "h", "ŀ": "l" };
function fold(name) {
  return normName(name).replace(/[ıłøđßæœðþħŀ]/g, (c) => SPECIAL[c] || c).replace(/-/g, " ").replace(/\s+/g, " ").trim();
}

// Per-map folded index: exact folded-key -> ovr, plus tokenized entries so a short
// ESPN name can match its longer EA FC entry when the match is unambiguous.
const idxCache = {};
function foldedIndex(key) {
  if (key in idxCache) return idxCache[key];
  const m = load(key);
  if (!m) return (idxCache[key] = null);
  const exact = {}, entries = [];
  for (const [k, v] of Object.entries(m)) {
    const f = fold(k); if (exact[f] == null) exact[f] = v;
    const parts = f.split(" ").filter(Boolean);
    entries.push({ toks: new Set(parts), first: parts[0] || "", last: parts[parts.length - 1] || "", val: v });
  }
  return (idxCache[key] = { exact, entries });
}
// All query tokens contained in exactly one entry's tokens -> that rating (else null).
function tokenSubset(idx, qToks) {
  if (qToks.length < 2) return null; // too weak to disambiguate on one token
  let hit = null;
  for (const e of idx.entries) { if (qToks.every((t) => e.toks.has(t))) { if (hit != null && hit !== e.val) return null; hit = e.val; } }
  return hit;
}
// Bounded edit distance (returns >max early). Used only to accept near-identical first
// names (transliterations like Matvei/Matvey, Odisseas/Odysseas), never surnames.
function editDist(a, b, max) {
  if (Math.abs(a.length - b.length) > max) return max + 1;
  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    const cur = [i]; let best = i;
    for (let j = 1; j <= b.length; j++) {
      const c = a[i - 1] === b[j - 1] ? prev[j - 1] : 1 + Math.min(prev[j - 1], prev[j], cur[j - 1]);
      cur[j] = c; if (c < best) best = c;
    }
    if (best > max) return max + 1;
    prev = cur;
  }
  return prev[b.length];
}
// Are two FIRST names near-variants? (one a prefix of the other — Ben/Benjamin — or a
// 1-2 char transliteration diff — Matvei/Matvey, Aleksandr/Alexandr, Odisseas/Odysseas.)
function firstNameLike(a, b) {
  if (a === b) return true;
  if (a.length >= 3 && (a.startsWith(b) || b.startsWith(a))) return true;
  return Math.max(a.length, b.length) >= 4 && editDist(a, b, 2) <= 2;
}
// Surname + first-INITIAL match, when the first names are near-variants and the match is
// unique in the map. Catches EA-vs-ESPN spelling/transliteration diffs (benjamin/ben
// white, matvey/matvei safonov) without letting two DIFFERENT players collide (any
// conflicting-rating candidate → null). Requires a 2-token query and a real surname.
function surnameInitial(idx, qToks) {
  if (qToks.length < 2) return null;
  const qFirst = qToks[0], qLast = qToks[qToks.length - 1];
  if (!qFirst || qLast.length < 3) return null;
  let val = null;
  for (const e of idx.entries) {
    if (e.last !== qLast || e.first[0] !== qFirst[0] || !firstNameLike(qFirst, e.first)) continue;
    if (val != null && val !== e.val) return null; // two different players → refuse
    val = e.val;
  }
  return val;
}

// Soccer leagues (all rated by EA FC). A star who transfers between leagues (e.g.
// Lewandowski moving to MLS) may still be filed under his OLD league in EA FC's
// current edition, so a name missing from his new league's map is looked up across
// all soccer maps — but ONLY when that name is unique across them, so common names
// can't be mis-assigned.
const SOCCER = ["mls", "epl", "laliga", "bundesliga", "seriea", "ligue1", "nwsl"];
let _soccerUnique = null;
function soccerUnique() {
  if (_soccerUnique) return _soccerUnique;
  const count = {}, val = {};
  for (const lg of SOCCER) { const m = load(lg); if (!m) continue; for (const [k, v] of Object.entries(m)) { const f = fold(k); count[f] = (count[f] || 0) + 1; val[f] = v; } }
  _soccerUnique = {};
  for (const k in count) if (count[k] === 1) _soccerUnique[k] = val[k];
  return _soccerUnique;
}

// The player's OVR for the given season (year null = current), or null. Matching
// escalates: exact -> folded (special letters/hyphens) -> token-subset (a short
// name inside a longer EA FC entry) -> cross-league unique (a transferred star).
function ratingFor(sport, name, year) {
  const nm = name && normName(name);
  if (!nm) return null;
  const key = mapKey(sport, year);
  const m = load(key);
  if (m && typeof m[nm] === "number") return m[nm];
  const idx = foldedIndex(key);
  const f = fold(name);
  if (idx) {
    if (typeof idx.exact[f] === "number") return idx.exact[f];
    const qToks = f.split(" ").filter(Boolean);
    const t = tokenSubset(idx, qToks);
    if (typeof t === "number") return t;
    const s = surnameInitial(idx, qToks); // EA-vs-ESPN spelling/transliteration variants
    if (typeof s === "number") return s;
  }
  // Cross-league fallback for a transferred star (current season only).
  if (!year && SOCCER.includes(sport)) { const g = soccerUnique()[f]; if (typeof g === "number") return g; }
  return null;
}

// Which game a sport's ratings come from (for the "OVR" badge label), or null.
// Returns null when the sport/season has no map data (so a wired-but-empty source
// like CFB, or a season we don't have historical ratings for, shows no badge).
function publisher(sport, year) {
  if (!PUBLISHER[sport]) return null;
  const m = load(mapKey(sport, year));
  return m && Object.keys(m).length ? PUBLISHER[sport] : null;
}

module.exports = { ratingFor, publisher, fold, tokenSubset, surnameInitial }; // internals exported for tests
