// lib/ratings.js — video-game overall ratings looked up from committed maps
// (data/ratings/<sport>.json, name -> OVR), so the live server never pages
// EA/Sony at runtime. Maps are generated by `npm run gen-ratings` and committed
// (like the seeds). NFL/Madden is handled separately in lib/nfl.js.
//
// Coverage: MLS → EA Sports FC, MLB → MLB The Show. NBA/WNBA (2K) and NHL/CFB
// have no publicly accessible ratings feed, so they carry no map (and no badge).
const fs = require("fs");
const path = require("path");
const { normName } = require("./nfl-util.js");

const DIR = path.join(__dirname, "..", "data", "ratings");
const PUBLISHER = { mls: "EA FC", mlb: "MLB The Show" };
const cache = {};

function load(sport) {
  if (sport in cache) return cache[sport];
  try { cache[sport] = JSON.parse(fs.readFileSync(path.join(DIR, `${sport}.json`), "utf8")); }
  catch { cache[sport] = null; }
  return cache[sport];
}

// The player's current OVR, or null if unknown / no map for this sport.
function ratingFor(sport, name) {
  const m = load(sport);
  if (!m || !name) return null;
  const v = m[normName(name)];
  return typeof v === "number" ? v : null;
}

// Which game a sport's ratings come from (for the "OVR" badge label), or null.
const publisher = (sport) => PUBLISHER[sport] || null;

module.exports = { ratingFor, publisher };
